sudo: required
services:
    - docker

    #run tests over the Dev version
before_install:
    - docker build -f ./client/Dockerfile.dev -t phsprado/react-tests ./client

    #phase of tests
script:
    - docker run -e CI=true phsprado/react-tests npm test

    #here we build the prod images (still in Travis)
after_success:
    - docker build -t phsprado/complex-client ./client
    - docker build -t phsprado/complex-nginx ./nginx
    - docker build -t phsprado/complex-server ./server
    - docker build -t phsprado/complex-worker ./worker
    #phase of deploy images on Dockerhub
    #First, login to Dockerhub
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #push images to docker hub
    - docker push phsprado/complex-client
    - docker push phsprado/complex-nginx
    - docker push phsprado/complex-server
    - docker push phsprado/complex-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-1-306476627547
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
